### PR TITLE
Add feature to list devices.

### PR DESCRIPTION
**Pull request by Wind-stormger**

### CODE REVIEW

**Comment by AmirHmZz** [comment]
Do we need to add [pyserial](https://pypi.org/project/pyserial/) as dependency to `pyproject.toml`? As long as It is dependency of [mpremote](https://github.com/micropython/micropython/blob/master/tools/mpremote/setup.cfg#L21), I think there's no need to add it directly as dependency but we should specify version of `mpremote`.

**Comment by Wind-stormger** [comment]
Any version of mpremote uses pyserial.
But I think it is right to add it.

**Comment by AmirHmZz** [comment]
Thank you :)

**Comment by AmirHmZz** [comment]
Thanks, available in version `1.3.2`

**Pull request merged**
