### PR TITLE
Update pyproject.toml

### PR DESCRIPTION
**Pull request by Wind-stormger**
mpremote has been updated to 1.20.0.

### CODE REVIEW

**Comment by AmirHmZz** [comment]
Thank you. Marged and will be available in `v1.4`

**Comment by Wind-stormger** [comment]
Can you release it into pypi? The current installation of mpbridge will automatically downgrade mpreview to 0.4.0.

**Comment by Wind-stormger** [comment]
Perhaps 1.3.5 will do.

**Comment by AmirHmZz** [comment]
@Wind-stormger Ok I will. Actually I was waiting for `mpremote` to add some more features before migration to new `mpremote`. Some of things we've done here could be done with new `mpremote` functions.

**Comment by Wind-stormger** [comment]
https://github.com/micropython/micropython/pull/11777

You're right, hash will also be added to mpremote.

I think that's good news, it's getting better and better!

**Pull request merged**
