### PR TITLE
Added some --help description text, and revised some hint text.

### PR DESCRIPTION
**Pull request by Wind-stormger**
Workflow in development mode, Sync file and Clean Sync file are detailed in --help.

### CODE REVIEW

**Comment by Wind-stormger** [comment]
Time to update to PyPI 😄

**Comment by Wind-stormger** [comment]
I have drawn a flowchart.

**Comment by Wind-stormger** [comment]
You may be busy with other things~

Check it out if you have free time 😉

**Comment by AmirHmZz** [comment]
Thanks for doing this nice job! I've also checked the flowchart and it seems fine! 
Would you please add flowchart to `readme.md` in dev mode instruction?

**Comment by Wind-stormger** [comment]
Which typography would be suitable, perhaps portrait?

**Comment by AmirHmZz** [comment]
Thanks! I think the landscape one is more compact and better to be viewed in desktop.

**Comment by Wind-stormger** [comment]
Done~

**Comment by AmirHmZz** [comment]
Thank you!
I've reviewed your flowchart. I think it might be better to create a flowchart for sync command separately and add it too readme in sync section! Also it is better to have the -clean flag in sync flowchart too.

**Comment by AmirHmZz** [comment]
Thanks :)

**Comment by Wind-stormger** [comment]
@AmirHmZz 
[Discord link](https://discord.com/channels/574275045187125269/574275045611012097/1077113443926155345)

**Pull request merged**
